[[redirects]]
  from = "/Shopify-Auth0-Multipass"
  to = "/posts/2019/Shopify-Auth0-Multipass"

[[redirects]]
  from = "/posts/2019/authenticate-shopify-customers-with-auth0"
  to = "/posts/2019/Shopify-Auth0-Multipass"

[[redirects]]
  from = "/Shopify-Multipass"
  to = "/posts/2019/Shopify-Multipass"

[[redirects]]
  from = "/posts/2019/shopify-multipass-in-net-core-3-0"
  to = "/posts/2019/Shopify-Multipass"

[[redirects]]
  from = "/TalentLMS-Auth0-SAML"
  to = "/posts/2019/TalentLMS-Auth0-SAML"

[[redirects]]
  from = "/Hills-In-Chicago"
  to = "/posts/2014/Hills-In-Chicago"

[[redirects]]
  from = "/Mock-Controller-Url"
  to = "/posts/2017/Mock-Controller-Url"

[[redirects]]
  from = "/Auth0-Simple-Progressing-Profiling"
  to = "/posts/2019/Auth0-Simple-Progressing-Profiling"

[[redirects]]
  from = "/AzureADB2C-User-Secrets"
  to = "/posts/2018/AzureADB2C-User-Secrets"

[[redirects]]
  from = "/Assessment-Requirements"
  to = "/posts/2019/Assessment-Requirements"

[[redirects]]
  from = "/posts/2019/technical-assessment-requirements-and-first-pass"
  to = "/posts/2019/Assessment-Requirements"

[[redirects]]
  from = "/Assessment-Delete"
  to = "/posts/2019/Assessment-Delete"

[[redirects]]
  from = "/Assessment-Create"
  to = "/posts/2019/Assessment-Create"

[[redirects]]
  from = "/posts/2019/technical-assessment-adding-create-functionality"
  to = "/posts/2019/Assessment-Create"

[[redirects]]
  from = "/Assessment-Wrapup"
  to = "/posts/2019/Assessment-Wrapup"

[[redirects]]
  from = "/Hamburger-Experiment"
  to = "/posts/2018/Hamburger-Experiment"

[[redirects]]
  from ="/assets/david-rovani-resume.pdf"
  to = "/about"

[[redirects]]
  from ="/posts/2022/the-book-of-boba-fett-season-one-a-few-thoughts"
  to = "/posts/2022/The-Book-of-Boba-Fett-Season-1"

[[redirects]]
  from ="/posts/2019/auth0-progressive-profiling-proof-of-concept/"
  to = "/posts/2019/auth0-simple-progressing-profiling"

[[redirects]]
  from ="/posts/2020/12-days-of-exercisemas/"
  to = "/posts/2020/Twelve-Days-of-Exercisemas"

[[redirects]]
  from ="/posts/2019/using-saml-2-0-with-auth0-to-authenticate-users-in-talent-lms"
  to = "/posts/2019/TalentLMS-Auth0-SAML"

[[redirects]]
  from ="/posts/2020/another-year-in-review-2020/"
  to = "/posts/2020/Another-Year-In-Review"

[[redirects]]
  from ="/posts/2019/shopify-multipass-in-net-core-3-0"
  to = "/posts/2019/shopify-multipass"

[[redirects]]
  from ="/Auth0-Simple-Progressing-Profiling/"
  to = "/posts/2019/auth0-simple-progressing-profiling"

[[redirects]]
  from ="/posts/2017/mock-controller-s-user-and-url-properties-in-asp-net-core-mvc"
  to = "/posts/2017/mock-controller-url"

[[redirects]]
  from ="/posts/2018/using-azure-ad-b2-c-and-visual-studio-user-secrets"
  to = "/posts/2018/AzureADB2C-User-Secrets"

[[redirects]]
  from ="/Introducing-Vigil-Web-API"
  to = "/posts/2017/Introducing-Vigil-Web-API"

[[redirects]]
  from ="/Azure-Command-Queue"
  to = "/posts/2017/Azure-Command-Queue"

[[redirects]]
  from ="/Revisiting-Creating-and-Updating-Entities"
  to = "/posts/2016/Revisiting-Creating-and-Updating-Entities"

[[redirects]]
  from ="/Project-BQ"
  to = "/posts/2019/Project-BQ"

[[redirects]]
  from ="/Explicit-Model-Constructor"
  to = "/posts/2017/Explicit-Model-Constructor"

[[redirects]]
  from ="/posts/2017/using-an-explicit-model-constructor-with-a-json-input-formatter"
  to = "/posts/2017/Explicit-Model-Constructor"

[[redirects]]
  from ="/Explicit-Model-Constructor"
  to = "/posts/2017/Explicit-Model-Constructor"

[[redirects]]
  from ="/Commit-4b684657"
  to = "/posts/2015/Laying-the-Foundation"

[[redirects]]
  from ="/Commit-8c41b3dc"
  to = "/posts/2015/Vigil-Base-Solution"

[[redirects]]
  from ="/posts/2019/first-week-at-blue-bolt-solutions"
  to = "/posts/2019/BlueBolt-First-Week"

[[redirects]]
  from ="/opt/build/repo/rovaninet-posts/2022/2022-02-03-first-rudimentary-mercenary-components.md"
  to = "/posts/2022/first-rudimentary-mercenary-components"

[[redirects]]
  from ="/star-wars-commentary"
  to = "/series/star-wars-commentary"

# Category posts list used to be pagenated; that has been removed with the NextJs migration
[[redirects]]
  from = "/category/:category/:page"
  to = "/category/:category"
  force = true

# Tag posts list used to be pagenated; that has been removed with the NextJs migration
[[redirects]]
  from = "/tag/:tag/:page"
  to = "/tag/:tag"
  force = true
